### ISSUE TITLE
Question: Input types

### ISSUE THREAD

**Issue by uniquenode** [BramKaashoek/typescript-typedefs#2]
Hello,

I was wondering whether it is also possible to generate input types?

Thank you

**Comment by BramKaashoek** [comment]
It is. An example can be found in the readme.

**Comment by uniquenode** [comment]
@BramKaashoek Thank you for your reply. Also, currently in `getGraphqlTypeFromType` you are always determining the type using getType from the Reflect API. In some cases (e.g. union types) it would be desired to use passedType or even just a string. Would you consider changing this?
